<a href="https://colab.research.google.com/github/Isai-Ramos/Librer-a-NUMPY-RamosRivera/blob/main/Librer%C3%ADa_NUMPY_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#creacion de vectores y manipulacion
import numpy as np
lista=[25,12,15,66,12.5]
vector=np.array(lista)
print(vector)
print("vector original")
print(vector)

print("sumarle 1 a cada elemento del vector:")
print(vector+1)
print("multiplicar por 5 cada elemento del vector:")
print(vector*5)

print("suma de los elementos:")
print(np.sum(vector))

print("promedio de los elementos:")
print(np.mean(vector)) # 

print("el vector sumado a si mismo:")
print(vector+vector)
print("suma de vectores vector1 y vector2 (mismo tamaño):")
vector2=np.array([11,55,1.2,7.4,-8])
print(vector+vector2)

[25.  12.  15.  66.  12.5]


In [3]:
#slices
lista=[25,12,15,66,12.5]
vector=np.array(lista)
print(vector)
print(vector[3])
print(vector[1:4])
print(vector[1:])
print(vector[:4])
print(vector[:])

[25.  12.  15.  66.  12.5]
66.0
[12. 15. 66.]
[12.  15.  66.  12.5]
[25. 12. 15. 66.]
[25.  12.  15.  66.  12.5]


In [5]:
 print("Vector de ceros:")
vector_ceros=np.zeros(5)
print(vector_ceros)

print("- Vector de unos:")
vector_unos=np.ones(5)
print(vector_unos)


print("Vector con todos los elementos con valor 2:")
vector_dos=np.zeros(5)+2
print(vector_dos)

print("Vector con todos los elementos con valor 2 (otra forma):")
vector_dos_otro=np.ones((5))*2
print(vector_dos_otro)

Vector de ceros:
[0. 0. 0. 0. 0.]
- Vector de unos:
[1. 1. 1. 1. 1.]
Vector con todos los elementos con valor 2:
[2. 2. 2. 2. 2.]
Vector con todos los elementos con valor 2 (otra forma):
[2. 2. 2. 2. 2.]


In [10]:
print("Matriz creada con una lista de listas:")
lista_de_listas=[ [1  ,-4], 
                  [12 , 3], 
                  [7.2, 5]]
matriz = np.array(lista_de_listas)
print(matriz)


print("Matriz creada con np.zeros:")
dimensiones=(2,3)
matriz_ceros = np.zeros(dimensiones)
print(matriz_ceros)


print("Matriz creada con np.ones:")
dimensiones=(3,2)
matriz_unos = np.ones(dimensiones)
print(matriz_unos)

print("Copia de la matriz creada con np.ones:")
matriz_unos_copia=np.copy(matriz_unos)
print(matriz_unos_copia)
#ejemplo
print("Ejemplo")
matriz_1=np.copy(matriz)
print(matriz_1)

Matriz creada con una lista de listas:
[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]
Matriz creada con np.zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
Matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Copia de la matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Ejemplo
[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]


In [11]:
lista_de_listas=[ [1  ,-4], 
                  [12 , 3], 
                  [7.2, 5]]
a = np.array(lista_de_listas)

print("Elementos individuales")
print(a[0,1])
print(a[2,1])

print("Vector de elementos de la fila 1")
print(a[1,:])

print("Vector de elementos de la columna 0")
print(a[:,0])

print("Submatriz de 2x2 con las primeras dos filas")
print(a[0:2,:])

print("Submatriz de 2x2 con las ultimas dos filas")
print(a[1:3,:])

Elementos individuales
-4.0
5.0
Vector de elementos de la fila 1
[12.  3.]
Vector de elementos de la columna 0
[ 1.  12.   7.2]
Submatriz de 2x2 con las primeras dos filas
[[ 1. -4.]
 [12.  3.]]
Submatriz de 2x2 con las ultimas dos filas
[[12.   3. ]
 [ 7.2  5. ]]


In [12]:
lista_de_listas=[ [1,-4], 
                  [12,3], 
                  [7, 5.0]]
a = np.array(lista_de_listas)

print("- Matriz original:")
print(a)

print("- Le asignamos el valor 4 a los elementos de la columna 0:")
a[:,0]=4
print(a)


print("- Dividimos por 3 la columna 1:")
a[:,1]=a[:,1]/3.0
print(a)

print("- Multiplicamos por 5 la fila 1:")
a[1,:]=a[1,:]*5
print(a)

print("- Le sumamos 1 a toda la matriz:")
a=a+1
print(a)

- Matriz original:
[[ 1. -4.]
 [12.  3.]
 [ 7.  5.]]
- Le asignamos el valor 4 a los elementos de la columna 0:
[[ 4. -4.]
 [ 4.  3.]
 [ 4.  5.]]
- Dividimos por 3 la columna 1:
[[ 4.         -1.33333333]
 [ 4.          1.        ]
 [ 4.          1.66666667]]
- Multiplicamos por 5 la fila 1:
[[ 4.         -1.33333333]
 [20.          5.        ]
 [ 4.          1.66666667]]
- Le sumamos 1 a toda la matriz:
[[ 5.         -0.33333333]
 [21.          6.        ]
 [ 5.          2.66666667]]


In [20]:
array=[[1, 2, 3],
       [4, 5, 6]]
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)

np.savetxt('lamatriz.txt',matriz)

[[1 2 3]
 [4 5 6]]


In [22]:
a = np.arange(0, 9).reshape(3, 3) 
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
